// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.serranomobile.sandbox.domains;

import com.serranomobile.sandbox.domains.User;
import java.util.Date;

privileged aspect User_Roo_JavaBean {
    
    public String User.getId() {
        return this.id;
    }
    
    public void User.setId(String id) {
        this.id = id;
    }
    
    public String User.getFirstName() {
        return this.firstName;
    }
    
    public void User.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String User.getLastName() {
        return this.lastName;
    }
    
    public void User.setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public Date User.getDateCreated() {
        return this.dateCreated;
    }
    
    public void User.setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
}
