// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.serranomobile.sandbox.domains;

import com.serranomobile.sandbox.domains.User;
import java.math.BigInteger;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Persistent;

privileged aspect User_Roo_Mongo_Entity {
    
    declare @type: User: @Persistent;
    
    @Id
    private BigInteger User.id_;
    
    public BigInteger User.getId_() {
        return this.id_;
    }
    
    public void User.setId_(BigInteger id) {
        this.id_ = id;
    }
    
}
